"""Auto-generated XWiki REST API methods.

This file is generated by scripts/generate_client.py from the XWiki WADL.
Do not edit manually; re-run the generator instead.
"""

from typing import Any, Dict, Optional


class GeneratedMethodsMixin:
    """Mixin that adds one Python method per WADL resource/method."""

    def get_wiki_space_page_attachment(self, wiki, space, page, attachment, *, raw: bool = True, accept: str = 'application/json', headers: Optional[Dict[str, str]] = None) -> Any:
        """GET /wikis/{wikiName}/spaces/{spaceName: .+}/pages/{pageName}/attachments/{attachmentName}"""

        path = f"/rest/wikis/{self._quote(wiki)}/spaces/{self._quote(space)}/pages/{self._quote(page)}/attachments/{self._quote(attachment)}"

        return self.request(method='GET', path=path, headers=headers, accept=accept, raw=True)

    def delete_wiki_space_page_attachment(self, wiki, space, page, attachment, *, raw: bool = False, accept: str = 'application/json', headers: Optional[Dict[str, str]] = None) -> Any:
        """DELETE /wikis/{wikiName}/spaces/{spaceName: .+}/pages/{pageName}/attachments/{attachmentName}"""

        path = f"/rest/wikis/{self._quote(wiki)}/spaces/{self._quote(space)}/pages/{self._quote(page)}/attachments/{self._quote(attachment)}"

        return self.request(method='DELETE', path=path, headers=headers, accept=accept, raw=False)

    def put_wiki_space_page_attachment(self, wiki, space, page, attachment, *, body: Optional[Any] = None, content_type: Optional[str] = None, raw: bool = False, accept: str = 'application/json', headers: Optional[Dict[str, str]] = None) -> Any:
        """PUT /wikis/{wikiName}/spaces/{spaceName: .+}/pages/{pageName}/attachments/{attachmentName}"""

        path = f"/rest/wikis/{self._quote(wiki)}/spaces/{self._quote(space)}/pages/{self._quote(page)}/attachments/{self._quote(attachment)}"

        return self.request(method='PUT', path=path, headers=headers, accept=accept, raw=False, body=body, content_type=content_type)

    def get_icons(self, *, name: Optional[Any] = None, raw: bool = False, accept: str = 'application/json', headers: Optional[Dict[str, str]] = None) -> Any:
        """GET /icons"""

        path = f"/rest/icons"

        params: Dict[str, Any] = {}
        if name is not None:
            params['name'] = name
        if params:
            path += '?' + self._urlencode(params)

        return self.request(method='GET', path=path, headers=headers, accept=accept, raw=False)

    def get_icon_theme_icons(self, icon_theme, *, name: Optional[Any] = None, raw: bool = False, accept: str = 'application/json', headers: Optional[Dict[str, str]] = None) -> Any:
        """GET /{iconTheme}/icons"""

        path = f"/rest/{self._quote(icon_theme)}/icons"

        params: Dict[str, Any] = {}
        if name is not None:
            params['name'] = name
        if params:
            path += '?' + self._urlencode(params)

        return self.request(method='GET', path=path, headers=headers, accept=accept, raw=False)

    def get_wiki_space_page_history_version_objects(self, wiki, space, page, version, *, start: Optional[Any] = 0, number: Optional[Any] = -1, pretty_names: Optional[Any] = False, raw: bool = False, accept: str = 'application/json', headers: Optional[Dict[str, str]] = None) -> Any:
        """GET /wikis/{wikiName}/spaces/{spaceName: .+}/pages/{pageName}/history/{version}/objects"""

        path = f"/rest/wikis/{self._quote(wiki)}/spaces/{self._quote(space)}/pages/{self._quote(page)}/history/{self._quote(version)}/objects"

        params: Dict[str, Any] = {}
        if start is not None:
            params['start'] = start
        if number is not None:
            params['number'] = number
        if pretty_names is not None:
            params['prettyNames'] = pretty_names
        if params:
            path += '?' + self._urlencode(params)

        return self.request(method='GET', path=path, headers=headers, accept=accept, raw=False)

    def get_wiki_space_page_objects_class_name(self, wiki, space, page, class_name, *, start: Optional[Any] = 0, number: Optional[Any] = -1, pretty_names: Optional[Any] = False, raw: bool = False, accept: str = 'application/json', headers: Optional[Dict[str, str]] = None) -> Any:
        """GET /wikis/{wikiName}/spaces/{spaceName: .+}/pages/{pageName}/objects/{className}"""

        path = f"/rest/wikis/{self._quote(wiki)}/spaces/{self._quote(space)}/pages/{self._quote(page)}/objects/{self._quote(class_name)}"

        params: Dict[str, Any] = {}
        if start is not None:
            params['start'] = start
        if number is not None:
            params['number'] = number
        if pretty_names is not None:
            params['prettyNames'] = pretty_names
        if params:
            path += '?' + self._urlencode(params)

        return self.request(method='GET', path=path, headers=headers, accept=accept, raw=False)

    def get_wikis(self, *, raw: bool = False, accept: str = 'application/json', headers: Optional[Dict[str, str]] = None) -> Any:
        """GET /wikis"""

        path = f"/rest/wikis"

        return self.request(method='GET', path=path, headers=headers, accept=accept, raw=False)

    def get_wiki_pages(self, wiki, *, start: Optional[Any] = 0, name: Optional[Any] = '', space: Optional[Any] = '', author: Optional[Any] = '', number: Optional[Any] = 25, raw: bool = False, accept: str = 'application/json', headers: Optional[Dict[str, str]] = None) -> Any:
        """GET /wikis/{wikiName}/pages"""

        path = f"/rest/wikis/{self._quote(wiki)}/pages"

        params: Dict[str, Any] = {}
        if start is not None:
            params['start'] = start
        if name is not None:
            params['name'] = name
        if space is not None:
            params['space'] = space
        if author is not None:
            params['author'] = author
        if number is not None:
            params['number'] = number
        if params:
            path += '?' + self._urlencode(params)

        return self.request(method='GET', path=path, headers=headers, accept=accept, raw=False)

    def get_jobstatus_job_id(self, job_id, *, request: Optional[Any] = False, progress: Optional[Any] = True, log: Optional[Any] = False, log_from_level: Optional[Any] = None, raw: bool = False, accept: str = 'application/json', headers: Optional[Dict[str, str]] = None) -> Any:
        """GET /jobstatus/{jobId: .+}"""

        path = f"/rest/jobstatus/{self._quote(job_id)}"

        params: Dict[str, Any] = {}
        if request is not None:
            params['request'] = request
        if progress is not None:
            params['progress'] = progress
        if log is not None:
            params['log'] = log
        if log_from_level is not None:
            params['log_fromLevel'] = log_from_level
        if params:
            path += '?' + self._urlencode(params)

        return self.request(method='GET', path=path, headers=headers, accept=accept, raw=False)

    def get_live_data_sources(self, *, namespace: Optional[Any] = '', raw: bool = False, accept: str = 'application/json', headers: Optional[Dict[str, str]] = None) -> Any:
        """GET /liveData/sources"""

        path = f"/rest/liveData/sources"

        params: Dict[str, Any] = {}
        if namespace is not None:
            params['namespace'] = namespace
        if params:
            path += '?' + self._urlencode(params)

        return self.request(method='GET', path=path, headers=headers, accept=accept, raw=False)

    def get_wiki_space_page_objects_class_name_object_number_properties(self, wiki, space, page, class_name, object_number, *, pretty_names: Optional[Any] = False, raw: bool = False, accept: str = 'application/json', headers: Optional[Dict[str, str]] = None) -> Any:
        """GET /wikis/{wikiName}/spaces/{spaceName: .+}/pages/{pageName}/objects/{className}/{objectNumber}/properties"""

        path = f"/rest/wikis/{self._quote(wiki)}/spaces/{self._quote(space)}/pages/{self._quote(page)}/objects/{self._quote(class_name)}/{self._quote(object_number)}/properties"

        params: Dict[str, Any] = {}
        if pretty_names is not None:
            params['prettyNames'] = pretty_names
        if params:
            path += '?' + self._urlencode(params)

        return self.request(method='GET', path=path, headers=headers, accept=accept, raw=False)

    def get_wiki_space_page_attachment_history_version(self, wiki, space, page, attachment, version, *, raw: bool = False, accept: str = 'application/json', headers: Optional[Dict[str, str]] = None) -> Any:
        """GET /wikis/{wikiName}/spaces/{spaceName: .+}/pages/{pageName}/attachments/{attachmentName}/history/{attachmentVersion}"""

        path = f"/rest/wikis/{self._quote(wiki)}/spaces/{self._quote(space)}/pages/{self._quote(page)}/attachments/{self._quote(attachment)}/history/{self._quote(version)}"

        return self.request(method='GET', path=path, headers=headers, accept=accept, raw=False)

    def get_wiki_space_page(self, wiki, space, page, *, pretty_names: Optional[Any] = False, objects: Optional[Any] = False, class_: Optional[Any] = False, attachments: Optional[Any] = False, raw: bool = False, accept: str = 'application/json', headers: Optional[Dict[str, str]] = None) -> Any:
        """GET /wikis/{wikiName}/spaces/{spaceName: .+}/pages/{pageName}"""

        path = f"/rest/wikis/{self._quote(wiki)}/spaces/{self._quote(space)}/pages/{self._quote(page)}"

        params: Dict[str, Any] = {}
        if pretty_names is not None:
            params['prettyNames'] = pretty_names
        if objects is not None:
            params['objects'] = objects
        if class_ is not None:
            params['class'] = class_
        if attachments is not None:
            params['attachments'] = attachments
        if params:
            path += '?' + self._urlencode(params)

        return self.request(method='GET', path=path, headers=headers, accept=accept, raw=False)

    def put_wiki_space_page(self, wiki, space, page, *, minor_revision: Optional[Any] = None, body: Optional[Any] = None, content_type: Optional[str] = None, raw: bool = False, accept: str = 'application/json', headers: Optional[Dict[str, str]] = None) -> Any:
        """PUT /wikis/{wikiName}/spaces/{spaceName: .+}/pages/{pageName}"""

        path = f"/rest/wikis/{self._quote(wiki)}/spaces/{self._quote(space)}/pages/{self._quote(page)}"

        params: Dict[str, Any] = {}
        if minor_revision is not None:
            params['minorRevision'] = minor_revision
        if params:
            path += '?' + self._urlencode(params)

        return self.request(method='PUT', path=path, headers=headers, accept=accept, raw=False, body=body, content_type=content_type)

    def delete_wiki_space_page(self, wiki, space, page, *, raw: bool = False, accept: str = 'application/json', headers: Optional[Dict[str, str]] = None) -> Any:
        """DELETE /wikis/{wikiName}/spaces/{spaceName: .+}/pages/{pageName}"""

        path = f"/rest/wikis/{self._quote(wiki)}/spaces/{self._quote(space)}/pages/{self._quote(page)}"

        return self.request(method='DELETE', path=path, headers=headers, accept=accept, raw=False)

    def get_wiki_space_search(self, wiki, space, *, q: Optional[Any] = None, scope: Optional[Any] = None, number: Optional[Any] = -1, start: Optional[Any] = 0, order_field: Optional[Any] = None, order: Optional[Any] = 'asc', pretty_names: Optional[Any] = False, locale_aware: Optional[Any] = False, raw: bool = False, accept: str = 'application/json', headers: Optional[Dict[str, str]] = None) -> Any:
        """GET /wikis/{wikiName}/spaces/{spaceName: .+}/search"""

        path = f"/rest/wikis/{self._quote(wiki)}/spaces/{self._quote(space)}/search"

        params: Dict[str, Any] = {}
        if q is not None:
            params['q'] = q
        if scope is not None:
            params['scope'] = scope
        if number is not None:
            params['number'] = number
        if start is not None:
            params['start'] = start
        if order_field is not None:
            params['orderField'] = order_field
        if order is not None:
            params['order'] = order
        if pretty_names is not None:
            params['prettyNames'] = pretty_names
        if locale_aware is not None:
            params['localeAware'] = locale_aware
        if params:
            path += '?' + self._urlencode(params)

        return self.request(method='GET', path=path, headers=headers, accept=accept, raw=False)

    def get_wiki_space_page_translations_language_annotations(self, wiki, space, page, language, *, raw: bool = False, accept: str = 'application/json', headers: Optional[Dict[str, str]] = None) -> Any:
        """GET /wikis/{wikiName}/spaces/{spaceName: .+}/pages/{pageName}/translations/{language}/annotations"""

        path = f"/rest/wikis/{self._quote(wiki)}/spaces/{self._quote(space)}/pages/{self._quote(page)}/translations/{self._quote(language)}/annotations"

        return self.request(method='GET', path=path, headers=headers, accept=accept, raw=False)

    def post_wiki_space_page_translations_language_annotations(self, wiki, space, page, language, *, body: Optional[Any] = None, content_type: Optional[str] = None, raw: bool = False, accept: str = 'application/json', headers: Optional[Dict[str, str]] = None) -> Any:
        """POST /wikis/{wikiName}/spaces/{spaceName: .+}/pages/{pageName}/translations/{language}/annotations"""

        path = f"/rest/wikis/{self._quote(wiki)}/spaces/{self._quote(space)}/pages/{self._quote(page)}/translations/{self._quote(language)}/annotations"

        return self.request(method='POST', path=path, headers=headers, accept=accept, raw=False, body=body, content_type=content_type)

    def get_wiki_space_page_history_version_objects_class_name_object_number(self, wiki, space, page, version, class_name, object_number, *, pretty_names: Optional[Any] = False, raw: bool = False, accept: str = 'application/json', headers: Optional[Dict[str, str]] = None) -> Any:
        """GET /wikis/{wikiName}/spaces/{spaceName: .+}/pages/{pageName}/history/{version}/objects/{className}/{objectNumber}"""

        path = f"/rest/wikis/{self._quote(wiki)}/spaces/{self._quote(space)}/pages/{self._quote(page)}/history/{self._quote(version)}/objects/{self._quote(class_name)}/{self._quote(object_number)}"

        params: Dict[str, Any] = {}
        if pretty_names is not None:
            params['prettyNames'] = pretty_names
        if params:
            path += '?' + self._urlencode(params)

        return self.request(method='GET', path=path, headers=headers, accept=accept, raw=False)

    def get_live_data_sources_source_id_properties(self, source_id, *, namespace: Optional[Any] = '', raw: bool = False, accept: str = 'application/json', headers: Optional[Dict[str, str]] = None) -> Any:
        """GET /liveData/sources/{sourceId}/properties"""

        path = f"/rest/liveData/sources/{self._quote(source_id)}/properties"

        params: Dict[str, Any] = {}
        if namespace is not None:
            params['namespace'] = namespace
        if params:
            path += '?' + self._urlencode(params)

        return self.request(method='GET', path=path, headers=headers, accept=accept, raw=False)

    def post_live_data_sources_source_id_properties(self, source_id, *, namespace: Optional[Any] = '', body: Optional[Any] = None, content_type: Optional[str] = None, raw: bool = False, accept: str = 'application/json', headers: Optional[Dict[str, str]] = None) -> Any:
        """POST /liveData/sources/{sourceId}/properties"""

        path = f"/rest/liveData/sources/{self._quote(source_id)}/properties"

        params: Dict[str, Any] = {}
        if namespace is not None:
            params['namespace'] = namespace
        if params:
            path += '?' + self._urlencode(params)

        return self.request(method='POST', path=path, headers=headers, accept=accept, raw=False, body=body, content_type=content_type)

    def get_live_data_sources_source_id_entries_entry_id_properties_property_id(self, source_id, entry_id, property_id, *, namespace: Optional[Any] = '', raw: bool = False, accept: str = 'application/json', headers: Optional[Dict[str, str]] = None) -> Any:
        """GET /liveData/sources/{sourceId}/entries/{entryId}/properties/{propertyId}"""

        path = f"/rest/liveData/sources/{self._quote(source_id)}/entries/{self._quote(entry_id)}/properties/{self._quote(property_id)}"

        params: Dict[str, Any] = {}
        if namespace is not None:
            params['namespace'] = namespace
        if params:
            path += '?' + self._urlencode(params)

        return self.request(method='GET', path=path, headers=headers, accept=accept, raw=False)

    def put_live_data_sources_source_id_entries_entry_id_properties_property_id(self, source_id, entry_id, property_id, *, namespace: Optional[Any] = '', body: Optional[Any] = None, content_type: Optional[str] = None, raw: bool = False, accept: str = 'application/json', headers: Optional[Dict[str, str]] = None) -> Any:
        """PUT /liveData/sources/{sourceId}/entries/{entryId}/properties/{propertyId}"""

        path = f"/rest/liveData/sources/{self._quote(source_id)}/entries/{self._quote(entry_id)}/properties/{self._quote(property_id)}"

        params: Dict[str, Any] = {}
        if namespace is not None:
            params['namespace'] = namespace
        if params:
            path += '?' + self._urlencode(params)

        return self.request(method='PUT', path=path, headers=headers, accept=accept, raw=False, body=body, content_type=content_type)

    def get_notifications(self, *, use_user_preferences: Optional[Any] = None, user_id: Optional[Any] = None, until_date: Optional[Any] = None, until_date_included: Optional[Any] = True, black_list: Optional[Any] = None, pages: Optional[Any] = None, spaces: Optional[Any] = None, wikis: Optional[Any] = None, users: Optional[Any] = None, count: Optional[Any] = None, display_own_events: Optional[Any] = None, display_minor_events: Optional[Any] = None, display_system_events: Optional[Any] = None, display_read_events: Optional[Any] = None, display_read_status: Optional[Any] = None, tags: Optional[Any] = None, current_wiki: Optional[Any] = None, async_: Optional[Any] = None, async_id: Optional[Any] = None, target: Optional[Any] = 'alert', raw: bool = False, accept: str = 'application/json', headers: Optional[Dict[str, str]] = None) -> Any:
        """GET /notifications"""

        path = f"/rest/notifications"

        params: Dict[str, Any] = {}
        if use_user_preferences is not None:
            params['useUserPreferences'] = use_user_preferences
        if user_id is not None:
            params['userId'] = user_id
        if until_date is not None:
            params['untilDate'] = until_date
        if until_date_included is not None:
            params['untilDateIncluded'] = until_date_included
        if black_list is not None:
            params['blackList'] = black_list
        if pages is not None:
            params['pages'] = pages
        if spaces is not None:
            params['spaces'] = spaces
        if wikis is not None:
            params['wikis'] = wikis
        if users is not None:
            params['users'] = users
        if count is not None:
            params['count'] = count
        if display_own_events is not None:
            params['displayOwnEvents'] = display_own_events
        if display_minor_events is not None:
            params['displayMinorEvents'] = display_minor_events
        if display_system_events is not None:
            params['displaySystemEvents'] = display_system_events
        if display_read_events is not None:
            params['displayReadEvents'] = display_read_events
        if display_read_status is not None:
            params['displayReadStatus'] = display_read_status
        if tags is not None:
            params['tags'] = tags
        if current_wiki is not None:
            params['currentWiki'] = current_wiki
        if async_ is not None:
            params['async'] = async_
        if async_id is not None:
            params['asyncId'] = async_id
        if target is not None:
            params['target'] = target
        if params:
            path += '?' + self._urlencode(params)

        return self.request(method='GET', path=path, headers=headers, accept=accept, raw=False)

    def post_notifications(self, *, body: Optional[Any] = None, content_type: Optional[str] = 'application/x-www-form-urlencoded', raw: bool = False, accept: str = 'application/json', headers: Optional[Dict[str, str]] = None) -> Any:
        """POST /notifications"""

        path = f"/rest/notifications"

        return self.request(method='POST', path=path, headers=headers, accept=accept, raw=False, body=body, content_type=content_type)

    def get_rss(self, *, use_user_preferences: Optional[Any] = None, user_id: Optional[Any] = None, until_date: Optional[Any] = None, black_list: Optional[Any] = None, pages: Optional[Any] = None, spaces: Optional[Any] = None, wikis: Optional[Any] = None, users: Optional[Any] = None, count: Optional[Any] = None, display_own_events: Optional[Any] = None, display_minor_events: Optional[Any] = None, display_system_events: Optional[Any] = None, display_read_events: Optional[Any] = None, display_read_status: Optional[Any] = None, tags: Optional[Any] = None, current_wiki: Optional[Any] = None, raw: bool = False, accept: str = 'application/json', headers: Optional[Dict[str, str]] = None) -> Any:
        """GET /rss"""

        path = f"/rest/rss"

        params: Dict[str, Any] = {}
        if use_user_preferences is not None:
            params['useUserPreferences'] = use_user_preferences
        if user_id is not None:
            params['userId'] = user_id
        if until_date is not None:
            params['untilDate'] = until_date
        if black_list is not None:
            params['blackList'] = black_list
        if pages is not None:
            params['pages'] = pages
        if spaces is not None:
            params['spaces'] = spaces
        if wikis is not None:
            params['wikis'] = wikis
        if users is not None:
            params['users'] = users
        if count is not None:
            params['count'] = count
        if display_own_events is not None:
            params['displayOwnEvents'] = display_own_events
        if display_minor_events is not None:
            params['displayMinorEvents'] = display_minor_events
        if display_system_events is not None:
            params['displaySystemEvents'] = display_system_events
        if display_read_events is not None:
            params['displayReadEvents'] = display_read_events
        if display_read_status is not None:
            params['displayReadStatus'] = display_read_status
        if tags is not None:
            params['tags'] = tags
        if current_wiki is not None:
            params['currentWiki'] = current_wiki
        if params:
            path += '?' + self._urlencode(params)

        return self.request(method='GET', path=path, headers=headers, accept=accept, raw=False)

    def get_count(self, *, use_user_preferences: Optional[Any] = None, user_id: Optional[Any] = None, pages: Optional[Any] = None, spaces: Optional[Any] = None, wikis: Optional[Any] = None, users: Optional[Any] = None, count: Optional[Any] = None, display_own_events: Optional[Any] = None, display_minor_events: Optional[Any] = None, display_system_events: Optional[Any] = None, display_read_events: Optional[Any] = None, display_read_status: Optional[Any] = None, tags: Optional[Any] = None, current_wiki: Optional[Any] = None, async_: Optional[Any] = None, async_id: Optional[Any] = None, raw: bool = False, accept: str = 'application/json', headers: Optional[Dict[str, str]] = None) -> Any:
        """GET /count"""

        path = f"/rest/count"

        params: Dict[str, Any] = {}
        if use_user_preferences is not None:
            params['useUserPreferences'] = use_user_preferences
        if user_id is not None:
            params['userId'] = user_id
        if pages is not None:
            params['pages'] = pages
        if spaces is not None:
            params['spaces'] = spaces
        if wikis is not None:
            params['wikis'] = wikis
        if users is not None:
            params['users'] = users
        if count is not None:
            params['count'] = count
        if display_own_events is not None:
            params['displayOwnEvents'] = display_own_events
        if display_minor_events is not None:
            params['displayMinorEvents'] = display_minor_events
        if display_system_events is not None:
            params['displaySystemEvents'] = display_system_events
        if display_read_events is not None:
            params['displayReadEvents'] = display_read_events
        if display_read_status is not None:
            params['displayReadStatus'] = display_read_status
        if tags is not None:
            params['tags'] = tags
        if current_wiki is not None:
            params['currentWiki'] = current_wiki
        if async_ is not None:
            params['async'] = async_
        if async_id is not None:
            params['asyncId'] = async_id
        if params:
            path += '?' + self._urlencode(params)

        return self.request(method='GET', path=path, headers=headers, accept=accept, raw=False)

    def get_wiki_search(self, wiki, *, q: Optional[Any] = None, scope: Optional[Any] = None, number: Optional[Any] = -1, start: Optional[Any] = 0, order_field: Optional[Any] = '', order: Optional[Any] = 'asc', pretty_names: Optional[Any] = False, locale_aware: Optional[Any] = False, raw: bool = False, accept: str = 'application/json', headers: Optional[Dict[str, str]] = None) -> Any:
        """GET /wikis/{wikiName}/search"""

        path = f"/rest/wikis/{self._quote(wiki)}/search"

        params: Dict[str, Any] = {}
        if q is not None:
            params['q'] = q
        if scope is not None:
            params['scope'] = scope
        if number is not None:
            params['number'] = number
        if start is not None:
            params['start'] = start
        if order_field is not None:
            params['orderField'] = order_field
        if order is not None:
            params['order'] = order
        if pretty_names is not None:
            params['prettyNames'] = pretty_names
        if locale_aware is not None:
            params['localeAware'] = locale_aware
        if params:
            path += '?' + self._urlencode(params)

        return self.request(method='GET', path=path, headers=headers, accept=accept, raw=False)

    def get_live_data_sources_source_id(self, source_id, *, namespace: Optional[Any] = '', raw: bool = False, accept: str = 'application/json', headers: Optional[Dict[str, str]] = None) -> Any:
        """GET /liveData/sources/{sourceId}"""

        path = f"/rest/liveData/sources/{self._quote(source_id)}"

        params: Dict[str, Any] = {}
        if namespace is not None:
            params['namespace'] = namespace
        if params:
            path += '?' + self._urlencode(params)

        return self.request(method='GET', path=path, headers=headers, accept=accept, raw=False)

    def get_wiki_space_page_history(self, wiki, space, page, *, start: Optional[Any] = 0, number: Optional[Any] = -1, order: Optional[Any] = 'desc', pretty_names: Optional[Any] = False, raw: bool = False, accept: str = 'application/json', headers: Optional[Dict[str, str]] = None) -> Any:
        """GET /wikis/{wikiName}/spaces/{spaceName: .+}/pages/{pageName}/history"""

        path = f"/rest/wikis/{self._quote(wiki)}/spaces/{self._quote(space)}/pages/{self._quote(page)}/history"

        params: Dict[str, Any] = {}
        if start is not None:
            params['start'] = start
        if number is not None:
            params['number'] = number
        if order is not None:
            params['order'] = order
        if pretty_names is not None:
            params['prettyNames'] = pretty_names
        if params:
            path += '?' + self._urlencode(params)

        return self.request(method='GET', path=path, headers=headers, accept=accept, raw=False)

    def get_wiki_space_page_annotations(self, wiki, space, page, *, raw: bool = False, accept: str = 'application/json', headers: Optional[Dict[str, str]] = None) -> Any:
        """GET /wikis/{wikiName}/spaces/{spaceName: .+}/pages/{pageName}/annotations"""

        path = f"/rest/wikis/{self._quote(wiki)}/spaces/{self._quote(space)}/pages/{self._quote(page)}/annotations"

        return self.request(method='GET', path=path, headers=headers, accept=accept, raw=False)

    def post_wiki_space_page_annotations(self, wiki, space, page, *, body: Optional[Any] = None, content_type: Optional[str] = None, raw: bool = False, accept: str = 'application/json', headers: Optional[Dict[str, str]] = None) -> Any:
        """POST /wikis/{wikiName}/spaces/{spaceName: .+}/pages/{pageName}/annotations"""

        path = f"/rest/wikis/{self._quote(wiki)}/spaces/{self._quote(space)}/pages/{self._quote(page)}/annotations"

        return self.request(method='POST', path=path, headers=headers, accept=accept, raw=False, body=body, content_type=content_type)

    def get_wiki_localization_translations(self, wiki, *, locale: Optional[Any] = None, prefix: Optional[Any] = None, key: Optional[Any] = None, raw: bool = False, accept: str = 'application/json', headers: Optional[Dict[str, str]] = None) -> Any:
        """GET /wikis/{wikiName}/localization/translations"""

        path = f"/rest/wikis/{self._quote(wiki)}/localization/translations"

        params: Dict[str, Any] = {}
        if locale is not None:
            params['locale'] = locale
        if prefix is not None:
            params['prefix'] = prefix
        if key is not None:
            params['key'] = key
        if params:
            path += '?' + self._urlencode(params)

        return self.request(method='GET', path=path, headers=headers, accept=accept, raw=False)

    def get_wiki_modifications(self, wiki, *, start: Optional[Any] = 0, number: Optional[Any] = 25, order: Optional[Any] = 'desc', date: Optional[Any] = 0, pretty_names: Optional[Any] = False, raw: bool = False, accept: str = 'application/json', headers: Optional[Dict[str, str]] = None) -> Any:
        """GET /wikis/{wikiName}/modifications"""

        path = f"/rest/wikis/{self._quote(wiki)}/modifications"

        params: Dict[str, Any] = {}
        if start is not None:
            params['start'] = start
        if number is not None:
            params['number'] = number
        if order is not None:
            params['order'] = order
        if date is not None:
            params['date'] = date
        if pretty_names is not None:
            params['prettyNames'] = pretty_names
        if params:
            path += '?' + self._urlencode(params)

        return self.request(method='GET', path=path, headers=headers, accept=accept, raw=False)

    def get_wiki_space_page_history_version_comments(self, wiki, space, page, version, *, start: Optional[Any] = 0, number: Optional[Any] = -1, pretty_names: Optional[Any] = False, raw: bool = False, accept: str = 'application/json', headers: Optional[Dict[str, str]] = None) -> Any:
        """GET /wikis/{wikiName}/spaces/{spaceName: .+}/pages/{pageName}/history/{version}/comments"""

        path = f"/rest/wikis/{self._quote(wiki)}/spaces/{self._quote(space)}/pages/{self._quote(page)}/history/{self._quote(version)}/comments"

        params: Dict[str, Any] = {}
        if start is not None:
            params['start'] = start
        if number is not None:
            params['number'] = number
        if pretty_names is not None:
            params['prettyNames'] = pretty_names
        if params:
            path += '?' + self._urlencode(params)

        return self.request(method='GET', path=path, headers=headers, accept=accept, raw=False)

    def get_wiki_classes(self, wiki, *, start: Optional[Any] = 0, number: Optional[Any] = -1, raw: bool = False, accept: str = 'application/json', headers: Optional[Dict[str, str]] = None) -> Any:
        """GET /wikis/{wikiName}/classes"""

        path = f"/rest/wikis/{self._quote(wiki)}/classes"

        params: Dict[str, Any] = {}
        if start is not None:
            params['start'] = start
        if number is not None:
            params['number'] = number
        if params:
            path += '?' + self._urlencode(params)

        return self.request(method='GET', path=path, headers=headers, accept=accept, raw=False)

    def get_wiki_classes_class_name_property(self, wiki, class_name, property, *, raw: bool = False, accept: str = 'application/json', headers: Optional[Dict[str, str]] = None) -> Any:
        """GET /wikis/{wikiName}/classes/{className}/properties/{propertyName}"""

        path = f"/rest/wikis/{self._quote(wiki)}/classes/{self._quote(class_name)}/properties/{self._quote(property)}"

        return self.request(method='GET', path=path, headers=headers, accept=accept, raw=False)

    def get_wiki_space_page_history_version_attachment(self, wiki, space, page, version, attachment, *, raw: bool = True, accept: str = 'application/json', headers: Optional[Dict[str, str]] = None) -> Any:
        """GET /wikis/{wikiName}/spaces/{spaceName: .+}/pages/{pageName}/history/{version}/attachments/{attachmentName}"""

        path = f"/rest/wikis/{self._quote(wiki)}/spaces/{self._quote(space)}/pages/{self._quote(page)}/history/{self._quote(version)}/attachments/{self._quote(attachment)}"

        return self.request(method='GET', path=path, headers=headers, accept=accept, raw=True)

    def get_wiki_query(self, wiki, *, q: Optional[Any] = None, type_: Optional[Any] = None, number: Optional[Any] = -1, start: Optional[Any] = 0, distinct: Optional[Any] = True, order_field: Optional[Any] = '', order: Optional[Any] = 'asc', pretty_names: Optional[Any] = False, class_name: Optional[Any] = '', raw: bool = False, accept: str = 'application/json', headers: Optional[Dict[str, str]] = None) -> Any:
        """GET /wikis/{wikiName}/query"""

        path = f"/rest/wikis/{self._quote(wiki)}/query"

        params: Dict[str, Any] = {}
        if q is not None:
            params['q'] = q
        if type_ is not None:
            params['type'] = type_
        if number is not None:
            params['number'] = number
        if start is not None:
            params['start'] = start
        if distinct is not None:
            params['distinct'] = distinct
        if order_field is not None:
            params['orderField'] = order_field
        if order is not None:
            params['order'] = order
        if pretty_names is not None:
            params['prettyNames'] = pretty_names
        if class_name is not None:
            params['className'] = class_name
        if params:
            path += '?' + self._urlencode(params)

        return self.request(method='GET', path=path, headers=headers, accept=accept, raw=False)

    def get_wiki_children(self, wiki, *, offset: Optional[Any] = 0, limit: Optional[Any] = -1, search: Optional[Any] = '', raw: bool = False, accept: str = 'application/json', headers: Optional[Dict[str, str]] = None) -> Any:
        """GET /wikis/{wikiName}/children"""

        path = f"/rest/wikis/{self._quote(wiki)}/children"

        params: Dict[str, Any] = {}
        if offset is not None:
            params['offset'] = offset
        if limit is not None:
            params['limit'] = limit
        if search is not None:
            params['search'] = search
        if params:
            path += '?' + self._urlencode(params)

        return self.request(method='GET', path=path, headers=headers, accept=accept, raw=False)

    def get_joblog_job_id(self, job_id, *, level: Optional[Any] = None, from_level: Optional[Any] = None, raw: bool = False, accept: str = 'application/json', headers: Optional[Dict[str, str]] = None) -> Any:
        """GET /joblog/{jobId: .+}"""

        path = f"/rest/joblog/{self._quote(job_id)}"

        params: Dict[str, Any] = {}
        if level is not None:
            params['level'] = level
        if from_level is not None:
            params['fromLevel'] = from_level
        if params:
            path += '?' + self._urlencode(params)

        return self.request(method='GET', path=path, headers=headers, accept=accept, raw=False)

    def get_wiki_tags_tag_names(self, wiki, tag_names, *, start: Optional[Any] = 0, number: Optional[Any] = -1, pretty_names: Optional[Any] = False, raw: bool = False, accept: str = 'application/json', headers: Optional[Dict[str, str]] = None) -> Any:
        """GET /wikis/{wikiName}/tags/{tagNames}"""

        path = f"/rest/wikis/{self._quote(wiki)}/tags/{self._quote(tag_names)}"

        params: Dict[str, Any] = {}
        if start is not None:
            params['start'] = start
        if number is not None:
            params['number'] = number
        if pretty_names is not None:
            params['prettyNames'] = pretty_names
        if params:
            path += '?' + self._urlencode(params)

        return self.request(method='GET', path=path, headers=headers, accept=accept, raw=False)

    def get_wiki_space_page_history_version_objects_class_name_object_number_property(self, wiki, space, page, version, class_name, object_number, property, *, pretty_names: Optional[Any] = False, raw: bool = False, accept: str = 'application/json', headers: Optional[Dict[str, str]] = None) -> Any:
        """GET /wikis/{wikiName}/spaces/{spaceName: .+}/pages/{pageName}/history/{version}/objects/{className}/{objectNumber}/properties/{propertyName}"""

        path = f"/rest/wikis/{self._quote(wiki)}/spaces/{self._quote(space)}/pages/{self._quote(page)}/history/{self._quote(version)}/objects/{self._quote(class_name)}/{self._quote(object_number)}/properties/{self._quote(property)}"

        params: Dict[str, Any] = {}
        if pretty_names is not None:
            params['prettyNames'] = pretty_names
        if params:
            path += '?' + self._urlencode(params)

        return self.request(method='GET', path=path, headers=headers, accept=accept, raw=False)

    def get_wiki_space_page_history_version_attachments(self, wiki, space, page, version, *, start: Optional[Any] = 0, number: Optional[Any] = -1, pretty_names: Optional[Any] = False, raw: bool = False, accept: str = 'application/json', headers: Optional[Dict[str, str]] = None) -> Any:
        """GET /wikis/{wikiName}/spaces/{spaceName: .+}/pages/{pageName}/history/{version}/attachments"""

        path = f"/rest/wikis/{self._quote(wiki)}/spaces/{self._quote(space)}/pages/{self._quote(page)}/history/{self._quote(version)}/attachments"

        params: Dict[str, Any] = {}
        if start is not None:
            params['start'] = start
        if number is not None:
            params['number'] = number
        if pretty_names is not None:
            params['prettyNames'] = pretty_names
        if params:
            path += '?' + self._urlencode(params)

        return self.request(method='GET', path=path, headers=headers, accept=accept, raw=False)

    def get_live_data_sources_source_id_properties_property_id(self, source_id, property_id, *, namespace: Optional[Any] = '', raw: bool = False, accept: str = 'application/json', headers: Optional[Dict[str, str]] = None) -> Any:
        """GET /liveData/sources/{sourceId}/properties/{propertyId}"""

        path = f"/rest/liveData/sources/{self._quote(source_id)}/properties/{self._quote(property_id)}"

        params: Dict[str, Any] = {}
        if namespace is not None:
            params['namespace'] = namespace
        if params:
            path += '?' + self._urlencode(params)

        return self.request(method='GET', path=path, headers=headers, accept=accept, raw=False)

    def put_live_data_sources_source_id_properties_property_id(self, source_id, property_id, *, namespace: Optional[Any] = '', body: Optional[Any] = None, content_type: Optional[str] = None, raw: bool = False, accept: str = 'application/json', headers: Optional[Dict[str, str]] = None) -> Any:
        """PUT /liveData/sources/{sourceId}/properties/{propertyId}"""

        path = f"/rest/liveData/sources/{self._quote(source_id)}/properties/{self._quote(property_id)}"

        params: Dict[str, Any] = {}
        if namespace is not None:
            params['namespace'] = namespace
        if params:
            path += '?' + self._urlencode(params)

        return self.request(method='PUT', path=path, headers=headers, accept=accept, raw=False, body=body, content_type=content_type)

    def delete_live_data_sources_source_id_properties_property_id(self, source_id, property_id, *, namespace: Optional[Any] = '', raw: bool = False, accept: str = 'application/json', headers: Optional[Dict[str, str]] = None) -> Any:
        """DELETE /liveData/sources/{sourceId}/properties/{propertyId}"""

        path = f"/rest/liveData/sources/{self._quote(source_id)}/properties/{self._quote(property_id)}"

        params: Dict[str, Any] = {}
        if namespace is not None:
            params['namespace'] = namespace
        if params:
            path += '?' + self._urlencode(params)

        return self.request(method='DELETE', path=path, headers=headers, accept=accept, raw=False)

    def get_wiki_space_attachments(self, wiki, space, *, name: Optional[Any] = '', page: Optional[Any] = '', author: Optional[Any] = '', types: Optional[Any] = '', start: Optional[Any] = 0, number: Optional[Any] = 25, pretty_names: Optional[Any] = False, raw: bool = False, accept: str = 'application/json', headers: Optional[Dict[str, str]] = None) -> Any:
        """GET /wikis/{wikiName}/spaces/{spaceName: .+}/attachments"""

        path = f"/rest/wikis/{self._quote(wiki)}/spaces/{self._quote(space)}/attachments"

        params: Dict[str, Any] = {}
        if name is not None:
            params['name'] = name
        if page is not None:
            params['page'] = page
        if author is not None:
            params['author'] = author
        if types is not None:
            params['types'] = types
        if start is not None:
            params['start'] = start
        if number is not None:
            params['number'] = number
        if pretty_names is not None:
            params['prettyNames'] = pretty_names
        if params:
            path += '?' + self._urlencode(params)

        return self.request(method='GET', path=path, headers=headers, accept=accept, raw=False)

    def get_wiki_space(self, wiki, space, *, raw: bool = False, accept: str = 'application/json', headers: Optional[Dict[str, str]] = None) -> Any:
        """GET /wikis/{wikiName}/spaces/{spaceName: .+}"""

        path = f"/rest/wikis/{self._quote(wiki)}/spaces/{self._quote(space)}"

        return self.request(method='GET', path=path, headers=headers, accept=accept, raw=False)

    def get_wiki_tags(self, wiki, *, raw: bool = False, accept: str = 'application/json', headers: Optional[Dict[str, str]] = None) -> Any:
        """GET /wikis/{wikiName}/tags"""

        path = f"/rest/wikis/{self._quote(wiki)}/tags"

        return self.request(method='GET', path=path, headers=headers, accept=accept, raw=False)

    def get_wiki_space_page_history_version_comments_id(self, wiki, space, page, version, id, *, start: Optional[Any] = 0, number: Optional[Any] = -1, pretty_names: Optional[Any] = False, raw: bool = False, accept: str = 'application/json', headers: Optional[Dict[str, str]] = None) -> Any:
        """GET /wikis/{wikiName}/spaces/{spaceName: .+}/pages/{pageName}/history/{version}/comments/{id}"""

        path = f"/rest/wikis/{self._quote(wiki)}/spaces/{self._quote(space)}/pages/{self._quote(page)}/history/{self._quote(version)}/comments/{self._quote(id)}"

        params: Dict[str, Any] = {}
        if start is not None:
            params['start'] = start
        if number is not None:
            params['number'] = number
        if pretty_names is not None:
            params['prettyNames'] = pretty_names
        if params:
            path += '?' + self._urlencode(params)

        return self.request(method='GET', path=path, headers=headers, accept=accept, raw=False)

    def get_wiki_space_page_objects(self, wiki, space, page, *, start: Optional[Any] = 0, number: Optional[Any] = -1, pretty_names: Optional[Any] = False, raw: bool = False, accept: str = 'application/json', headers: Optional[Dict[str, str]] = None) -> Any:
        """GET /wikis/{wikiName}/spaces/{spaceName: .+}/pages/{pageName}/objects"""

        path = f"/rest/wikis/{self._quote(wiki)}/spaces/{self._quote(space)}/pages/{self._quote(page)}/objects"

        params: Dict[str, Any] = {}
        if start is not None:
            params['start'] = start
        if number is not None:
            params['number'] = number
        if pretty_names is not None:
            params['prettyNames'] = pretty_names
        if params:
            path += '?' + self._urlencode(params)

        return self.request(method='GET', path=path, headers=headers, accept=accept, raw=False)

    def post_wiki_space_page_objects(self, wiki, space, page, *, minor_revision: Optional[Any] = None, body: Optional[Any] = None, content_type: Optional[str] = None, raw: bool = False, accept: str = 'application/json', headers: Optional[Dict[str, str]] = None) -> Any:
        """POST /wikis/{wikiName}/spaces/{spaceName: .+}/pages/{pageName}/objects"""

        path = f"/rest/wikis/{self._quote(wiki)}/spaces/{self._quote(space)}/pages/{self._quote(page)}/objects"

        params: Dict[str, Any] = {}
        if minor_revision is not None:
            params['minorRevision'] = minor_revision
        if params:
            path += '?' + self._urlencode(params)

        return self.request(method='POST', path=path, headers=headers, accept=accept, raw=False, body=body, content_type=content_type)

    def get_live_data_sources_source_id_types(self, source_id, *, namespace: Optional[Any] = '', raw: bool = False, accept: str = 'application/json', headers: Optional[Dict[str, str]] = None) -> Any:
        """GET /liveData/sources/{sourceId}/types"""

        path = f"/rest/liveData/sources/{self._quote(source_id)}/types"

        params: Dict[str, Any] = {}
        if namespace is not None:
            params['namespace'] = namespace
        if params:
            path += '?' + self._urlencode(params)

        return self.request(method='GET', path=path, headers=headers, accept=accept, raw=False)

    def put_currentuser_property_next(self, property, *, body: Optional[Any] = None, content_type: Optional[str] = None, raw: bool = False, accept: str = 'application/json', headers: Optional[Dict[str, str]] = None) -> Any:
        """PUT /currentuser/properties/{propertyName}/next"""

        path = f"/rest/currentuser/properties/{self._quote(property)}/next"

        return self.request(method='PUT', path=path, headers=headers, accept=accept, raw=False, body=body, content_type=content_type)

    def get_wiki_space_page_comments(self, wiki, space, page, *, start: Optional[Any] = 0, number: Optional[Any] = -1, pretty_names: Optional[Any] = False, raw: bool = False, accept: str = 'application/json', headers: Optional[Dict[str, str]] = None) -> Any:
        """GET /wikis/{wikiName}/spaces/{spaceName: .+}/pages/{pageName}/comments"""

        path = f"/rest/wikis/{self._quote(wiki)}/spaces/{self._quote(space)}/pages/{self._quote(page)}/comments"

        params: Dict[str, Any] = {}
        if start is not None:
            params['start'] = start
        if number is not None:
            params['number'] = number
        if pretty_names is not None:
            params['prettyNames'] = pretty_names
        if params:
            path += '?' + self._urlencode(params)

        return self.request(method='GET', path=path, headers=headers, accept=accept, raw=False)

    def post_wiki_space_page_comments(self, wiki, space, page, *, body: Optional[Any] = None, content_type: Optional[str] = None, raw: bool = False, accept: str = 'application/json', headers: Optional[Dict[str, str]] = None) -> Any:
        """POST /wikis/{wikiName}/spaces/{spaceName: .+}/pages/{pageName}/comments"""

        path = f"/rest/wikis/{self._quote(wiki)}/spaces/{self._quote(space)}/pages/{self._quote(page)}/comments"

        return self.request(method='POST', path=path, headers=headers, accept=accept, raw=False, body=body, content_type=content_type)

    def get_wiki_space_page_objects_class_name_object_number_property(self, wiki, space, page, class_name, object_number, property, *, pretty_names: Optional[Any] = False, raw: bool = False, accept: str = 'application/json', headers: Optional[Dict[str, str]] = None) -> Any:
        """GET /wikis/{wikiName}/spaces/{spaceName: .+}/pages/{pageName}/objects/{className}/{objectNumber}/properties/{propertyName}"""

        path = f"/rest/wikis/{self._quote(wiki)}/spaces/{self._quote(space)}/pages/{self._quote(page)}/objects/{self._quote(class_name)}/{self._quote(object_number)}/properties/{self._quote(property)}"

        params: Dict[str, Any] = {}
        if pretty_names is not None:
            params['prettyNames'] = pretty_names
        if params:
            path += '?' + self._urlencode(params)

        return self.request(method='GET', path=path, headers=headers, accept=accept, raw=False)

    def put_wiki_space_page_objects_class_name_object_number_property(self, wiki, space, page, class_name, object_number, property, *, minor_revision: Optional[Any] = None, body: Optional[Any] = None, content_type: Optional[str] = None, raw: bool = False, accept: str = 'application/json', headers: Optional[Dict[str, str]] = None) -> Any:
        """PUT /wikis/{wikiName}/spaces/{spaceName: .+}/pages/{pageName}/objects/{className}/{objectNumber}/properties/{propertyName}"""

        path = f"/rest/wikis/{self._quote(wiki)}/spaces/{self._quote(space)}/pages/{self._quote(page)}/objects/{self._quote(class_name)}/{self._quote(object_number)}/properties/{self._quote(property)}"

        params: Dict[str, Any] = {}
        if minor_revision is not None:
            params['minorRevision'] = minor_revision
        if params:
            path += '?' + self._urlencode(params)

        return self.request(method='PUT', path=path, headers=headers, accept=accept, raw=False, body=body, content_type=content_type)

    def get_wiki_space_page_channels(self, wiki, space, page, *, path: Optional[Any] = None, create: Optional[Any] = False, raw: bool = False, accept: str = 'application/json', headers: Optional[Dict[str, str]] = None) -> Any:
        """GET /wikis/{wikiName}/spaces/{spaceName: .+}/pages/{pageName}/channels"""

        path = f"/rest/wikis/{self._quote(wiki)}/spaces/{self._quote(space)}/pages/{self._quote(page)}/channels"

        params: Dict[str, Any] = {}
        if path is not None:
            params['path'] = path
        if create is not None:
            params['create'] = create
        if params:
            path += '?' + self._urlencode(params)

        return self.request(method='GET', path=path, headers=headers, accept=accept, raw=False)

    def get_wiki_space_page_attachment_metadata(self, wiki, space, page, attachment, *, pretty_names: Optional[Any] = False, raw: bool = False, accept: str = 'application/json', headers: Optional[Dict[str, str]] = None) -> Any:
        """GET /wikis/{wikiName}/spaces/{spaceName: .+}/pages/{pageName}/attachments/{attachmentName}/metadata"""

        path = f"/rest/wikis/{self._quote(wiki)}/spaces/{self._quote(space)}/pages/{self._quote(page)}/attachments/{self._quote(attachment)}/metadata"

        params: Dict[str, Any] = {}
        if pretty_names is not None:
            params['prettyNames'] = pretty_names
        if params:
            path += '?' + self._urlencode(params)

        return self.request(method='GET', path=path, headers=headers, accept=accept, raw=False)

    def delete_wiki_space_page_annotation_id(self, wiki, space, page, id, *, raw: bool = False, accept: str = 'application/json', headers: Optional[Dict[str, str]] = None) -> Any:
        """DELETE /wikis/{wikiName}/spaces/{spaceName: .+}/pages/{pageName}/annotation/{id}"""

        path = f"/rest/wikis/{self._quote(wiki)}/spaces/{self._quote(space)}/pages/{self._quote(page)}/annotation/{self._quote(id)}"

        return self.request(method='DELETE', path=path, headers=headers, accept=accept, raw=False)

    def put_wiki_space_page_annotation_id(self, wiki, space, page, id, *, body: Optional[Any] = None, content_type: Optional[str] = None, raw: bool = False, accept: str = 'application/json', headers: Optional[Dict[str, str]] = None) -> Any:
        """PUT /wikis/{wikiName}/spaces/{spaceName: .+}/pages/{pageName}/annotation/{id}"""

        path = f"/rest/wikis/{self._quote(wiki)}/spaces/{self._quote(space)}/pages/{self._quote(page)}/annotation/{self._quote(id)}"

        return self.request(method='PUT', path=path, headers=headers, accept=accept, raw=False, body=body, content_type=content_type)

    def put_jobs(self, *, job_type: Optional[Any] = None, async_: Optional[Any] = True, body: Optional[Any] = None, content_type: Optional[str] = None, raw: bool = False, accept: str = 'application/json', headers: Optional[Dict[str, str]] = None) -> Any:
        """PUT /jobs"""

        path = f"/rest/jobs"

        params: Dict[str, Any] = {}
        if job_type is not None:
            params['jobType'] = job_type
        if async_ is not None:
            params['async'] = async_
        if params:
            path += '?' + self._urlencode(params)

        return self.request(method='PUT', path=path, headers=headers, accept=accept, raw=False, body=body, content_type=content_type)

    def get_wiki_space_page_comments_id(self, wiki, space, page, id, *, start: Optional[Any] = 0, number: Optional[Any] = -1, pretty_names: Optional[Any] = False, raw: bool = False, accept: str = 'application/json', headers: Optional[Dict[str, str]] = None) -> Any:
        """GET /wikis/{wikiName}/spaces/{spaceName: .+}/pages/{pageName}/comments/{id}"""

        path = f"/rest/wikis/{self._quote(wiki)}/spaces/{self._quote(space)}/pages/{self._quote(page)}/comments/{self._quote(id)}"

        params: Dict[str, Any] = {}
        if start is not None:
            params['start'] = start
        if number is not None:
            params['number'] = number
        if pretty_names is not None:
            params['prettyNames'] = pretty_names
        if params:
            path += '?' + self._urlencode(params)

        return self.request(method='GET', path=path, headers=headers, accept=accept, raw=False)

    def get_syntaxes(self, *, raw: bool = False, accept: str = 'application/json', headers: Optional[Dict[str, str]] = None) -> Any:
        """GET /syntaxes"""

        path = f"/rest/syntaxes"

        return self.request(method='GET', path=path, headers=headers, accept=accept, raw=False)

    def get_wiki_space_page_translations_language(self, wiki, space, page, language, *, pretty_names: Optional[Any] = False, raw: bool = False, accept: str = 'application/json', headers: Optional[Dict[str, str]] = None) -> Any:
        """GET /wikis/{wikiName}/spaces/{spaceName: .+}/pages/{pageName}/translations/{language}"""

        path = f"/rest/wikis/{self._quote(wiki)}/spaces/{self._quote(space)}/pages/{self._quote(page)}/translations/{self._quote(language)}"

        params: Dict[str, Any] = {}
        if pretty_names is not None:
            params['prettyNames'] = pretty_names
        if params:
            path += '?' + self._urlencode(params)

        return self.request(method='GET', path=path, headers=headers, accept=accept, raw=False)

    def put_wiki_space_page_translations_language(self, wiki, space, page, language, *, minor_revision: Optional[Any] = None, body: Optional[Any] = None, content_type: Optional[str] = None, raw: bool = False, accept: str = 'application/json', headers: Optional[Dict[str, str]] = None) -> Any:
        """PUT /wikis/{wikiName}/spaces/{spaceName: .+}/pages/{pageName}/translations/{language}"""

        path = f"/rest/wikis/{self._quote(wiki)}/spaces/{self._quote(space)}/pages/{self._quote(page)}/translations/{self._quote(language)}"

        params: Dict[str, Any] = {}
        if minor_revision is not None:
            params['minorRevision'] = minor_revision
        if params:
            path += '?' + self._urlencode(params)

        return self.request(method='PUT', path=path, headers=headers, accept=accept, raw=False, body=body, content_type=content_type)

    def delete_wiki_space_page_translations_language(self, wiki, space, page, language, *, raw: bool = False, accept: str = 'application/json', headers: Optional[Dict[str, str]] = None) -> Any:
        """DELETE /wikis/{wikiName}/spaces/{spaceName: .+}/pages/{pageName}/translations/{language}"""

        path = f"/rest/wikis/{self._quote(wiki)}/spaces/{self._quote(space)}/pages/{self._quote(page)}/translations/{self._quote(language)}"

        return self.request(method='DELETE', path=path, headers=headers, accept=accept, raw=False)

    def get_wiki_attachments(self, wiki, *, name: Optional[Any] = '', page: Optional[Any] = '', space: Optional[Any] = '', author: Optional[Any] = '', types: Optional[Any] = '', start: Optional[Any] = 0, number: Optional[Any] = 25, pretty_names: Optional[Any] = False, raw: bool = False, accept: str = 'application/json', headers: Optional[Dict[str, str]] = None) -> Any:
        """GET /wikis/{wikiName}/attachments"""

        path = f"/rest/wikis/{self._quote(wiki)}/attachments"

        params: Dict[str, Any] = {}
        if name is not None:
            params['name'] = name
        if page is not None:
            params['page'] = page
        if space is not None:
            params['space'] = space
        if author is not None:
            params['author'] = author
        if types is not None:
            params['types'] = types
        if start is not None:
            params['start'] = start
        if number is not None:
            params['number'] = number
        if pretty_names is not None:
            params['prettyNames'] = pretty_names
        if params:
            path += '?' + self._urlencode(params)

        return self.request(method='GET', path=path, headers=headers, accept=accept, raw=False)

    def get_wiki_space_page_history_version(self, wiki, space, page, version, *, pretty_names: Optional[Any] = False, raw: bool = False, accept: str = 'application/json', headers: Optional[Dict[str, str]] = None) -> Any:
        """GET /wikis/{wikiName}/spaces/{spaceName: .+}/pages/{pageName}/history/{version}"""

        path = f"/rest/wikis/{self._quote(wiki)}/spaces/{self._quote(space)}/pages/{self._quote(page)}/history/{self._quote(version)}"

        params: Dict[str, Any] = {}
        if pretty_names is not None:
            params['prettyNames'] = pretty_names
        if params:
            path += '?' + self._urlencode(params)

        return self.request(method='GET', path=path, headers=headers, accept=accept, raw=False)

    def get_wiki_space_page_translations(self, wiki, space, page, *, raw: bool = False, accept: str = 'application/json', headers: Optional[Dict[str, str]] = None) -> Any:
        """GET /wikis/{wikiName}/spaces/{spaceName: .+}/pages/{pageName}/translations"""

        path = f"/rest/wikis/{self._quote(wiki)}/spaces/{self._quote(space)}/pages/{self._quote(page)}/translations"

        return self.request(method='GET', path=path, headers=headers, accept=accept, raw=False)

    def get_wiki_space_page_translations_language_history_version(self, wiki, space, page, language, version, *, pretty_names: Optional[Any] = False, raw: bool = False, accept: str = 'application/json', headers: Optional[Dict[str, str]] = None) -> Any:
        """GET /wikis/{wikiName}/spaces/{spaceName: .+}/pages/{pageName}/translations/{language}/history/{version}"""

        path = f"/rest/wikis/{self._quote(wiki)}/spaces/{self._quote(space)}/pages/{self._quote(page)}/translations/{self._quote(language)}/history/{self._quote(version)}"

        params: Dict[str, Any] = {}
        if pretty_names is not None:
            params['prettyNames'] = pretty_names
        if params:
            path += '?' + self._urlencode(params)

        return self.request(method='GET', path=path, headers=headers, accept=accept, raw=False)

    def get_live_data_sources_source_id_entries_entry_id(self, source_id, entry_id, *, namespace: Optional[Any] = '', raw: bool = False, accept: str = 'application/json', headers: Optional[Dict[str, str]] = None) -> Any:
        """GET /liveData/sources/{sourceId}/entries/{entryId}"""

        path = f"/rest/liveData/sources/{self._quote(source_id)}/entries/{self._quote(entry_id)}"

        params: Dict[str, Any] = {}
        if namespace is not None:
            params['namespace'] = namespace
        if params:
            path += '?' + self._urlencode(params)

        return self.request(method='GET', path=path, headers=headers, accept=accept, raw=False)

    def delete_live_data_sources_source_id_entries_entry_id(self, source_id, entry_id, *, namespace: Optional[Any] = '', raw: bool = False, accept: str = 'application/json', headers: Optional[Dict[str, str]] = None) -> Any:
        """DELETE /liveData/sources/{sourceId}/entries/{entryId}"""

        path = f"/rest/liveData/sources/{self._quote(source_id)}/entries/{self._quote(entry_id)}"

        params: Dict[str, Any] = {}
        if namespace is not None:
            params['namespace'] = namespace
        if params:
            path += '?' + self._urlencode(params)

        return self.request(method='DELETE', path=path, headers=headers, accept=accept, raw=False)

    def put_live_data_sources_source_id_entries_entry_id(self, source_id, entry_id, *, namespace: Optional[Any] = '', body: Optional[Any] = None, content_type: Optional[str] = None, raw: bool = False, accept: str = 'application/json', headers: Optional[Dict[str, str]] = None) -> Any:
        """PUT /liveData/sources/{sourceId}/entries/{entryId}"""

        path = f"/rest/liveData/sources/{self._quote(source_id)}/entries/{self._quote(entry_id)}"

        params: Dict[str, Any] = {}
        if namespace is not None:
            params['namespace'] = namespace
        if params:
            path += '?' + self._urlencode(params)

        return self.request(method='PUT', path=path, headers=headers, accept=accept, raw=False, body=body, content_type=content_type)

    def get_wiki_classes_class_name_properties(self, wiki, class_name, *, raw: bool = False, accept: str = 'application/json', headers: Optional[Dict[str, str]] = None) -> Any:
        """GET /wikis/{wikiName}/classes/{className}/properties"""

        path = f"/rest/wikis/{self._quote(wiki)}/classes/{self._quote(class_name)}/properties"

        return self.request(method='GET', path=path, headers=headers, accept=accept, raw=False)

    def get_wiki_space_page_attachments(self, wiki, space, page, *, start: Optional[Any] = 0, number: Optional[Any] = -1, pretty_names: Optional[Any] = False, name: Optional[Any] = '', author: Optional[Any] = '', types: Optional[Any] = '', raw: bool = False, accept: str = 'application/json', headers: Optional[Dict[str, str]] = None) -> Any:
        """GET /wikis/{wikiName}/spaces/{spaceName: .+}/pages/{pageName}/attachments"""

        path = f"/rest/wikis/{self._quote(wiki)}/spaces/{self._quote(space)}/pages/{self._quote(page)}/attachments"

        params: Dict[str, Any] = {}
        if start is not None:
            params['start'] = start
        if number is not None:
            params['number'] = number
        if pretty_names is not None:
            params['prettyNames'] = pretty_names
        if name is not None:
            params['name'] = name
        if author is not None:
            params['author'] = author
        if types is not None:
            params['types'] = types
        if params:
            path += '?' + self._urlencode(params)

        return self.request(method='GET', path=path, headers=headers, accept=accept, raw=False)

    def post_wiki_space_page_attachments(self, wiki, space, page, *, pretty_names: Optional[Any] = False, create_page: Optional[Any] = False, body: Optional[Any] = None, content_type: Optional[str] = 'multipart/form-data', raw: bool = False, accept: str = 'application/json', headers: Optional[Dict[str, str]] = None) -> Any:
        """POST /wikis/{wikiName}/spaces/{spaceName: .+}/pages/{pageName}/attachments"""

        path = f"/rest/wikis/{self._quote(wiki)}/spaces/{self._quote(space)}/pages/{self._quote(page)}/attachments"

        params: Dict[str, Any] = {}
        if pretty_names is not None:
            params['prettyNames'] = pretty_names
        if create_page is not None:
            params['createPage'] = create_page
        if params:
            path += '?' + self._urlencode(params)

        return self.request(method='POST', path=path, headers=headers, accept=accept, raw=False, body=body, content_type=content_type)

    def get_wiki_space_page_objects_class_name_object_number(self, wiki, space, page, class_name, object_number, *, pretty_names: Optional[Any] = False, raw: bool = False, accept: str = 'application/json', headers: Optional[Dict[str, str]] = None) -> Any:
        """GET /wikis/{wikiName}/spaces/{spaceName: .+}/pages/{pageName}/objects/{className}/{objectNumber}"""

        path = f"/rest/wikis/{self._quote(wiki)}/spaces/{self._quote(space)}/pages/{self._quote(page)}/objects/{self._quote(class_name)}/{self._quote(object_number)}"

        params: Dict[str, Any] = {}
        if pretty_names is not None:
            params['prettyNames'] = pretty_names
        if params:
            path += '?' + self._urlencode(params)

        return self.request(method='GET', path=path, headers=headers, accept=accept, raw=False)

    def put_wiki_space_page_objects_class_name_object_number(self, wiki, space, page, class_name, object_number, *, minor_revision: Optional[Any] = None, body: Optional[Any] = None, content_type: Optional[str] = None, raw: bool = False, accept: str = 'application/json', headers: Optional[Dict[str, str]] = None) -> Any:
        """PUT /wikis/{wikiName}/spaces/{spaceName: .+}/pages/{pageName}/objects/{className}/{objectNumber}"""

        path = f"/rest/wikis/{self._quote(wiki)}/spaces/{self._quote(space)}/pages/{self._quote(page)}/objects/{self._quote(class_name)}/{self._quote(object_number)}"

        params: Dict[str, Any] = {}
        if minor_revision is not None:
            params['minorRevision'] = minor_revision
        if params:
            path += '?' + self._urlencode(params)

        return self.request(method='PUT', path=path, headers=headers, accept=accept, raw=False, body=body, content_type=content_type)

    def delete_wiki_space_page_objects_class_name_object_number(self, wiki, space, page, class_name, object_number, *, raw: bool = False, accept: str = 'application/json', headers: Optional[Dict[str, str]] = None) -> Any:
        """DELETE /wikis/{wikiName}/spaces/{spaceName: .+}/pages/{pageName}/objects/{className}/{objectNumber}"""

        path = f"/rest/wikis/{self._quote(wiki)}/spaces/{self._quote(space)}/pages/{self._quote(page)}/objects/{self._quote(class_name)}/{self._quote(object_number)}"

        return self.request(method='DELETE', path=path, headers=headers, accept=accept, raw=False)

    def get_wiki_classes_class_name_property_values(self, wiki, class_name, property, *, limit: Optional[Any] = 100, fp: Optional[Any] = None, exact_match: Optional[Any] = False, raw: bool = False, accept: str = 'application/json', headers: Optional[Dict[str, str]] = None) -> Any:
        """GET /wikis/{wikiName}/classes/{className}/properties/{propertyName}/values"""

        path = f"/rest/wikis/{self._quote(wiki)}/classes/{self._quote(class_name)}/properties/{self._quote(property)}/values"

        params: Dict[str, Any] = {}
        if limit is not None:
            params['limit'] = limit
        if fp is not None:
            params['fp'] = fp
        if exact_match is not None:
            params['exactMatch'] = exact_match
        if params:
            path += '?' + self._urlencode(params)

        return self.request(method='GET', path=path, headers=headers, accept=accept, raw=False)

    def get_client(self, *, raw: bool = False, accept: str = 'application/json', headers: Optional[Dict[str, str]] = None) -> Any:
        """GET /client"""

        path = f"/rest/client"

        return self.request(method='GET', path=path, headers=headers, accept=accept, raw=False)

    def post_live_data_sources_source_id_entries(self, source_id, *, namespace: Optional[Any] = '', body: Optional[Any] = None, content_type: Optional[str] = None, raw: bool = False, accept: str = 'application/json', headers: Optional[Dict[str, str]] = None) -> Any:
        """POST /liveData/sources/{sourceId}/entries"""

        path = f"/rest/liveData/sources/{self._quote(source_id)}/entries"

        params: Dict[str, Any] = {}
        if namespace is not None:
            params['namespace'] = namespace
        if params:
            path += '?' + self._urlencode(params)

        return self.request(method='POST', path=path, headers=headers, accept=accept, raw=False, body=body, content_type=content_type)

    def get_live_data_sources_source_id_entries(self, source_id, *, namespace: Optional[Any] = '', properties: Optional[Any] = None, match_all: Optional[Any] = None, sort: Optional[Any] = None, descending: Optional[Any] = None, offset: Optional[Any] = 0, limit: Optional[Any] = 10, raw: bool = False, accept: str = 'application/json', headers: Optional[Dict[str, str]] = None) -> Any:
        """GET /liveData/sources/{sourceId}/entries"""

        path = f"/rest/liveData/sources/{self._quote(source_id)}/entries"

        params: Dict[str, Any] = {}
        if namespace is not None:
            params['namespace'] = namespace
        if properties is not None:
            params['properties'] = properties
        if match_all is not None:
            params['matchAll'] = match_all
        if sort is not None:
            params['sort'] = sort
        if descending is not None:
            params['descending'] = descending
        if offset is not None:
            params['offset'] = offset
        if limit is not None:
            params['limit'] = limit
        if params:
            path += '?' + self._urlencode(params)

        return self.request(method='GET', path=path, headers=headers, accept=accept, raw=False)

    def get_wiki(self, wiki, *, raw: bool = False, accept: str = 'application/json', headers: Optional[Dict[str, str]] = None) -> Any:
        """GET /wikis/{wikiName}"""

        path = f"/rest/wikis/{self._quote(wiki)}"

        return self.request(method='GET', path=path, headers=headers, accept=accept, raw=False)

    def post_wiki(self, wiki, *, backup: Optional[Any] = False, history: Optional[Any] = 'add', body: Optional[Any] = None, content_type: Optional[str] = None, raw: bool = False, accept: str = 'application/json', headers: Optional[Dict[str, str]] = None) -> Any:
        """POST /wikis/{wikiName}"""

        path = f"/rest/wikis/{self._quote(wiki)}"

        params: Dict[str, Any] = {}
        if backup is not None:
            params['backup'] = backup
        if history is not None:
            params['history'] = history
        if params:
            path += '?' + self._urlencode(params)

        return self.request(method='POST', path=path, headers=headers, accept=accept, raw=False, body=body, content_type=content_type)

    def get_wiki_space_page_attachment_history(self, wiki, space, page, attachment, *, start: Optional[Any] = 0, number: Optional[Any] = -1, raw: bool = False, accept: str = 'application/json', headers: Optional[Dict[str, str]] = None) -> Any:
        """GET /wikis/{wikiName}/spaces/{spaceName: .+}/pages/{pageName}/attachments/{attachmentName}/history"""

        path = f"/rest/wikis/{self._quote(wiki)}/spaces/{self._quote(space)}/pages/{self._quote(page)}/attachments/{self._quote(attachment)}/history"

        params: Dict[str, Any] = {}
        if start is not None:
            params['start'] = start
        if number is not None:
            params['number'] = number
        if params:
            path += '?' + self._urlencode(params)

        return self.request(method='GET', path=path, headers=headers, accept=accept, raw=False)

    def get_wiki_classes_class_name(self, wiki, class_name, *, raw: bool = False, accept: str = 'application/json', headers: Optional[Dict[str, str]] = None) -> Any:
        """GET /wikis/{wikiName}/classes/{className}"""

        path = f"/rest/wikis/{self._quote(wiki)}/classes/{self._quote(class_name)}"

        return self.request(method='GET', path=path, headers=headers, accept=accept, raw=False)

    def get_wiki_space_page_children(self, wiki, space, page, *, start: Optional[Any] = 0, number: Optional[Any] = -1, pretty_names: Optional[Any] = False, hierarchy: Optional[Any] = 'parentchild', search: Optional[Any] = '', raw: bool = False, accept: str = 'application/json', headers: Optional[Dict[str, str]] = None) -> Any:
        """GET /wikis/{wikiName}/spaces/{spaceName: .+}/pages/{pageName}/children"""

        path = f"/rest/wikis/{self._quote(wiki)}/spaces/{self._quote(space)}/pages/{self._quote(page)}/children"

        params: Dict[str, Any] = {}
        if start is not None:
            params['start'] = start
        if number is not None:
            params['number'] = number
        if pretty_names is not None:
            params['prettyNames'] = pretty_names
        if hierarchy is not None:
            params['hierarchy'] = hierarchy
        if search is not None:
            params['search'] = search
        if params:
            path += '?' + self._urlencode(params)

        return self.request(method='GET', path=path, headers=headers, accept=accept, raw=False)

    def get_wiki_space_page_history_version_objects_class_name_object_number_properties(self, wiki, space, page, version, class_name, object_number, *, pretty_names: Optional[Any] = False, raw: bool = False, accept: str = 'application/json', headers: Optional[Dict[str, str]] = None) -> Any:
        """GET /wikis/{wikiName}/spaces/{spaceName: .+}/pages/{pageName}/history/{version}/objects/{className}/{objectNumber}/properties"""

        path = f"/rest/wikis/{self._quote(wiki)}/spaces/{self._quote(space)}/pages/{self._quote(page)}/history/{self._quote(version)}/objects/{self._quote(class_name)}/{self._quote(object_number)}/properties"

        params: Dict[str, Any] = {}
        if pretty_names is not None:
            params['prettyNames'] = pretty_names
        if params:
            path += '?' + self._urlencode(params)

        return self.request(method='GET', path=path, headers=headers, accept=accept, raw=False)

    def get_live_data_sources_source_id_types_type_id(self, source_id, type_id, *, namespace: Optional[Any] = '', raw: bool = False, accept: str = 'application/json', headers: Optional[Dict[str, str]] = None) -> Any:
        """GET /liveData/sources/{sourceId}/types/{typeId}"""

        path = f"/rest/liveData/sources/{self._quote(source_id)}/types/{self._quote(type_id)}"

        params: Dict[str, Any] = {}
        if namespace is not None:
            params['namespace'] = namespace
        if params:
            path += '?' + self._urlencode(params)

        return self.request(method='GET', path=path, headers=headers, accept=accept, raw=False)

    def get_wiki_spaces(self, wiki, *, start: Optional[Any] = 0, number: Optional[Any] = -1, raw: bool = False, accept: str = 'application/json', headers: Optional[Dict[str, str]] = None) -> Any:
        """GET /wikis/{wikiName}/spaces"""

        path = f"/rest/wikis/{self._quote(wiki)}/spaces"

        params: Dict[str, Any] = {}
        if start is not None:
            params['start'] = start
        if number is not None:
            params['number'] = number
        if params:
            path += '?' + self._urlencode(params)

        return self.request(method='GET', path=path, headers=headers, accept=accept, raw=False)

    def get_wiki_classes_class_name_objects(self, wiki, class_name, *, start: Optional[Any] = 0, number: Optional[Any] = -1, order: Optional[Any] = None, pretty_names: Optional[Any] = False, raw: bool = False, accept: str = 'application/json', headers: Optional[Dict[str, str]] = None) -> Any:
        """GET /wikis/{wikiName}/classes/{className}/objects"""

        path = f"/rest/wikis/{self._quote(wiki)}/classes/{self._quote(class_name)}/objects"

        params: Dict[str, Any] = {}
        if start is not None:
            params['start'] = start
        if number is not None:
            params['number'] = number
        if order is not None:
            params['order'] = order
        if pretty_names is not None:
            params['prettyNames'] = pretty_names
        if params:
            path += '?' + self._urlencode(params)

        return self.request(method='GET', path=path, headers=headers, accept=accept, raw=False)

    def get_wiki_space_pages(self, wiki, space, *, start: Optional[Any] = 0, number: Optional[Any] = -1, parent_id: Optional[Any] = None, order: Optional[Any] = None, pretty_names: Optional[Any] = False, raw: bool = False, accept: str = 'application/json', headers: Optional[Dict[str, str]] = None) -> Any:
        """GET /wikis/{wikiName}/spaces/{spaceName: .+}/pages"""

        path = f"/rest/wikis/{self._quote(wiki)}/spaces/{self._quote(space)}/pages"

        params: Dict[str, Any] = {}
        if start is not None:
            params['start'] = start
        if number is not None:
            params['number'] = number
        if parent_id is not None:
            params['parentId'] = parent_id
        if order is not None:
            params['order'] = order
        if pretty_names is not None:
            params['prettyNames'] = pretty_names
        if params:
            path += '?' + self._urlencode(params)

        return self.request(method='GET', path=path, headers=headers, accept=accept, raw=False)

    def put_wiki_space_page_tags(self, wiki, space, page, *, minor_revision: Optional[Any] = None, body: Optional[Any] = None, content_type: Optional[str] = None, raw: bool = False, accept: str = 'application/json', headers: Optional[Dict[str, str]] = None) -> Any:
        """PUT /wikis/{wikiName}/spaces/{spaceName: .+}/pages/{pageName}/tags"""

        path = f"/rest/wikis/{self._quote(wiki)}/spaces/{self._quote(space)}/pages/{self._quote(page)}/tags"

        params: Dict[str, Any] = {}
        if minor_revision is not None:
            params['minorRevision'] = minor_revision
        if params:
            path += '?' + self._urlencode(params)

        return self.request(method='PUT', path=path, headers=headers, accept=accept, raw=False, body=body, content_type=content_type)

    def get_wiki_space_page_tags(self, wiki, space, page, *, raw: bool = False, accept: str = 'application/json', headers: Optional[Dict[str, str]] = None) -> Any:
        """GET /wikis/{wikiName}/spaces/{spaceName: .+}/pages/{pageName}/tags"""

        path = f"/rest/wikis/{self._quote(wiki)}/spaces/{self._quote(space)}/pages/{self._quote(page)}/tags"

        return self.request(method='GET', path=path, headers=headers, accept=accept, raw=False)

    def get_wiki_image_styles(self, wiki, *, raw: bool = False, accept: str = 'application/json', headers: Optional[Dict[str, str]] = None) -> Any:
        """GET /wikis/{wikiName}/imageStyles"""

        path = f"/rest/wikis/{self._quote(wiki)}/imageStyles"

        return self.request(method='GET', path=path, headers=headers, accept=accept, raw=False)

    def get_default(self, *, document_reference: Optional[Any] = None, raw: bool = False, accept: str = 'application/json', headers: Optional[Dict[str, str]] = None) -> Any:
        """GET /default"""

        path = f"/rest/default"

        params: Dict[str, Any] = {}
        if document_reference is not None:
            params['documentReference'] = document_reference
        if params:
            path += '?' + self._urlencode(params)

        return self.request(method='GET', path=path, headers=headers, accept=accept, raw=False)

    def get_wikis_query(self, *, q: Optional[Any] = None, number: Optional[Any] = -1, start: Optional[Any] = 0, distinct: Optional[Any] = True, wikis: Optional[Any] = None, order_field: Optional[Any] = '', order: Optional[Any] = 'asc', pretty_names: Optional[Any] = False, class_name: Optional[Any] = '', raw: bool = False, accept: str = 'application/json', headers: Optional[Dict[str, str]] = None) -> Any:
        """GET /wikis/query"""

        path = f"/rest/wikis/query"

        params: Dict[str, Any] = {}
        if q is not None:
            params['q'] = q
        if number is not None:
            params['number'] = number
        if start is not None:
            params['start'] = start
        if distinct is not None:
            params['distinct'] = distinct
        if wikis is not None:
            params['wikis'] = wikis
        if order_field is not None:
            params['orderField'] = order_field
        if order is not None:
            params['order'] = order
        if pretty_names is not None:
            params['prettyNames'] = pretty_names
        if class_name is not None:
            params['className'] = class_name
        if params:
            path += '?' + self._urlencode(params)

        return self.request(method='GET', path=path, headers=headers, accept=accept, raw=False)

    def get_wiki_space_page_translations_language_history(self, wiki, space, page, language, *, start: Optional[Any] = 0, number: Optional[Any] = -1, order: Optional[Any] = 'desc', pretty_names: Optional[Any] = False, raw: bool = False, accept: str = 'application/json', headers: Optional[Dict[str, str]] = None) -> Any:
        """GET /wikis/{wikiName}/spaces/{spaceName: .+}/pages/{pageName}/translations/{language}/history"""

        path = f"/rest/wikis/{self._quote(wiki)}/spaces/{self._quote(space)}/pages/{self._quote(page)}/translations/{self._quote(language)}/history"

        params: Dict[str, Any] = {}
        if start is not None:
            params['start'] = start
        if number is not None:
            params['number'] = number
        if order is not None:
            params['order'] = order
        if pretty_names is not None:
            params['prettyNames'] = pretty_names
        if params:
            path += '?' + self._urlencode(params)

        return self.request(method='GET', path=path, headers=headers, accept=accept, raw=False)

    def get_application_wadl(self, *, raw: bool = False, accept: str = 'application/json', headers: Optional[Dict[str, str]] = None) -> Any:
        """GET application.wadl"""

        path = f"/rest/application.wadl"

        return self.request(method='GET', path=path, headers=headers, accept=accept, raw=False)

    def get_path(self, path, *, raw: bool = False, accept: str = 'application/json', headers: Optional[Dict[str, str]] = None) -> Any:
        """GET {path}"""

        path = f"/rest/{self._quote(path)}"

        return self.request(method='GET', path=path, headers=headers, accept=accept, raw=False)
